// Do not alter this file, instead it should be generated by using `yarn svg`
// This will override this file and update the exported map for use in the SvgIcon component

import { FC } from 'react';
import ArrowRight from './arrow-right.svg';
import Avatar from './avatar.svg';
import BarChart from './bar-chart.svg';
import BurgerClose from './burger-close.svg';
import BurgerIcon from './burger-icon.svg';
import CalendarEmpty from './calendar-empty.svg';
import Calendar from './calendar.svg';
import Chain from './chain.svg';
import Chart from './chart.svg';
import CheckmarkCircle from './checkmark-circle.svg';
import Checkmark from './checkmark.svg';
import ChevronCircleRight from './chevron-circle-right.svg';
import ChevronDownFilled from './chevron-down-filled.svg';
import ChevronRight from './chevron-right.svg';
import CirclePlusInverted from './circle-plus-inverted.svg';
import CirclePlus from './circle-plus.svg';
import Clipboard from './clipboard.svg';
import ClockOutline from './clock-outline.svg';
import DocumentPage from './document-page.svg';
import DollarCrossed from './dollar-crossed.svg';
import Dollar from './dollar.svg';
import Email from './email.svg';
import ErrorTextIcon from './error-text-icon.svg';
import ExternalLink from './external-link.svg';
import EyeClosed from './eye-closed.svg';
import EyeOpen from './eye-open.svg';
import Eye from './eye.svg';
import Facebook from './facebook.svg';
import Filters from './filters.svg';
import FlagDk from './flag-dk.svg';
import FlagGb from './flag-gb.svg';
import FolderOutline from './folder-outline.svg';
import Folder from './folder.svg';
import Globe from './globe.svg';
import Hashtag from './hashtag.svg';
import Home from './home.svg';
import Hourglass from './hourglass.svg';
import Info from './info.svg';
import LinkedNodes from './linked-nodes.svg';
import Linkedin from './linkedin.svg';
import Location from './location.svg';
import LogOut from './log-out.svg';
import MagnifyingGlass from './magnifying-glass.svg';
import Mastercard from './mastercard.svg';
import MoneyBag from './money-bag.svg';
import Newspaper from './newspaper.svg';
import Page from './page.svg';
import Pencil from './pencil.svg';
import People from './people.svg';
import Phone from './phone.svg';
import Plus from './plus.svg';
import Projects from './projects.svg';
import RadioWaves from './radio-waves.svg';
import Report from './report.svg';
import Robot from './robot.svg';
import Running from './running.svg';
import SearchIcon from './search-icon.svg';
import Search from './search.svg';
import Settings from './settings.svg';
import Share from './share.svg';
import SignIn from './sign-in.svg';
import SignOut from './sign-out.svg';
import SliderArrowRight from './slider-arrow-right.svg';
import StrokePricing from './stroke-pricing.svg';
import StrokesHero from './strokes-hero.svg';
import SuccessMessage from './success-message.svg';
import ThreeDots from './three-dots.svg';
import Trash from './trash.svg';
import Triangle from './triangle.svg';
import Visa from './visa.svg';
import Warning from './warning.svg';
import Youtube from './youtube.svg';

export const TLAIcons: { [key: string]: FC<any> } = {
    arrowRight: ArrowRight,
    avatar: Avatar,
    barChart: BarChart,
    burgerClose: BurgerClose,
    burgerIcon: BurgerIcon,
    calendarEmpty: CalendarEmpty,
    calendar: Calendar,
    chain: Chain,
    chart: Chart,
    checkmarkCircle: CheckmarkCircle,
    checkmark: Checkmark,
    chevronCircleRight: ChevronCircleRight,
    chevronDownFilled: ChevronDownFilled,
    chevronRight: ChevronRight,
    circlePlusInverted: CirclePlusInverted,
    circlePlus: CirclePlus,
    clipboard: Clipboard,
    clockOutline: ClockOutline,
    documentPage: DocumentPage,
    dollarCrossed: DollarCrossed,
    dollar: Dollar,
    email: Email,
    errorTextIcon: ErrorTextIcon,
    externalLink: ExternalLink,
    eyeClosed: EyeClosed,
    eyeOpen: EyeOpen,
    eye: Eye,
    facebook: Facebook,
    filters: Filters,
    flagDk: FlagDk,
    flagGb: FlagGb,
    folderOutline: FolderOutline,
    folder: Folder,
    globe: Globe,
    hashtag: Hashtag,
    home: Home,
    hourglass: Hourglass,
    info: Info,
    linkedNodes: LinkedNodes,
    linkedin: Linkedin,
    location: Location,
    logOut: LogOut,
    magnifyingGlass: MagnifyingGlass,
    mastercard: Mastercard,
    moneyBag: MoneyBag,
    newspaper: Newspaper,
    page: Page,
    pencil: Pencil,
    people: People,
    phone: Phone,
    plus: Plus,
    projects: Projects,
    radioWaves: RadioWaves,
    report: Report,
    robot: Robot,
    running: Running,
    searchIcon: SearchIcon,
    search: Search,
    settings: Settings,
    share: Share,
    signIn: SignIn,
    signOut: SignOut,
    sliderArrowRight: SliderArrowRight,
    strokePricing: StrokePricing,
    strokesHero: StrokesHero,
    successMessage: SuccessMessage,
    threeDots: ThreeDots,
    trash: Trash,
    triangle: Triangle,
    visa: Visa,
    warning: Warning,
    youtube: Youtube,
}